### ISSUE TITLE
Building with `mpi+mpitrampoline` still uses MPICH

### ISSUE THREAD

**Issue by eschnett** [JuliaPackaging/Yggdrasil#4925]
I am trying to build `openPMD_api` with this command:
```sh
julia --color=yes build_tarballs.jl --debug --verbose --deploy=local x86_64-apple-darwin-julia_version+1.7.0-mpi+mpitrampoline
```
Although I am using `mpi+mpitrampoline`, I find that `$prefix/include/mpi.h` is from MPICH, not from MPItrampoline.

This is my [`build_tarballs.jl`](https://gist.github.com/eschnett/56f1ccfe51a703d97c5ee2e75ff6ecc8).

Is there a mistake in my script?

The same setup is working fine for the package `ADIOS2`. The main difference is that ADIOS2 does not depend on any other package that also depends on MPI. Maybe BinaryBuilder installs a wrong version of ADIOS2, one which depends on MPICH instead of MPItrampoline?

**Comment by giordano** [comment]
@staticfloat @vchuravy ideas?

**Comment by giordano** [comment]
So, the environment used for the target platform is
```toml
[deps]
ADIOS2_jll = "44b1415a-b224-5c99-9168-ff4febb5f37f"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
LibUV_jll = "183b4373-6708-53ba-ad28-60e28bb38547"
LibUnwind_jll = "745a5e78-f969-53e9-954f-d19f2f74f4e3"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MPItrampoline_jll = "f1f71cc9-e9ae-5b93-9b94-4fe0e1ad3748"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
libjulia_jll = "5ad3ddd2-0711-543a-b040-befd59781bbf"
```
My understanding is that the file [`ADIOS2_jll/.pkg/platform_augmentation.jl`](https://github.com/JuliaBinaryWrappers/ADIOS2_jll.jl/blob/25d3e067fcc4d1fcd61dfa621d852671593a6b50/.pkg/platform_augmentation.jl) is never actually loaded, so we don't know how to augment the platform and we basically install a random MPI implementation.  Even more worrying, also OpenMPI is in the manifest of the environment and gets automatically installed.

I believe we need a mechanism to properly filter the dependencies.  This is the first time we're venturing into this zone with the augmented platforms, it's a new territory for everyone.
