### ISSUE TITLE
The SLICOT_jll-v5.8 fails to link with Julia 1.8.0

### ISSUE THREAD

**Issue by andreasvarga** [JuliaPackaging/Yggdrasil#4969]
Recently the SLICOT library has been updated to v5.8 and the corresponding SLICOT_jll has been generated by courtesy of Ralph Smith. I uploaded the package and it works fine locally with Julia 1.7.2. However, running some CI tests, I got complaints of version incompatibility (see below) (e.g., on Julia ^1.8.0-0 - ubuntu-latest - x64 )

```
 
Run julia --color=yes --project=@. -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end'
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: Unsatisfiable requirements detected for package libblastrampoline_jll [8e850b90]:
 libblastrampoline_jll [8e850b90] log:
 ├─possible versions are: 5.1.0 or uninstalled
 └─found to have no compatible versions left with SLICOT_jll [545525a2]
```
I am not sure what this means, but looking to compatibilities of SLICOT_jll, there is
`libblastrampoline_jll = "3.0.4"`
I wonder if this covers all later versions (e.g., 5.1.0 mentioned above). 

Note that with with Julia 1.7.3 the tests run correctly!

**Comment by giordano** [comment]
Someone should do something like #4770 (for lack of better options at the moment)

**Comment by RalphAS** [comment]
Since this wraps a Fortran library we also have the proliferation of gfortran versions.  Is there any way to avoid combinatorial explosion?

**Comment by giordano** [comment]
Not really, sadly.

**Comment by andreasvarga** [comment]
A question: As I remember, with SLICOT_jll for v5.7, I executed all tests with both Julia 1.7 and 1.8 without problems. What is essentially different now with the version for v5.8?

**Comment by giordano** [comment]
> As I remember, with SLICOT_jll for v5.7, I executed all tests with both Julia 1.7 and 1.8 without problems.

I doubt it, as `SLICOT_jll` `v5.7` was already linking to libblastrampoline.

**Comment by andreasvarga** [comment]
I posted 4 (four) releases of [PeriodicSystems](https://github.com/andreasvarga/PeriodicSystems.jl). 
Releases v0.1, v0.2 and v0.3 were based on SLICOT_jll_v5.7 and I switched to SLICOT_jll_v5.8 in Release v0.3.1.
I extracted below from the history of `CI.yml` files the relevant settings for tests.

Release v0.1 was succesfully tested using
```
      matrix:
        version:
          - '1.7' 
          # - '1' 
          - 'nightly' 
        os:  [ubuntu-latest]
```  

Releases v0.2 and v0.3 were succesfully tested using
```
      matrix:
        version:
          - '1.7' 
          # - '1' 
          - '^1.8.0-0'
          # - 'nightly' 
        os:  
          - ubuntu-latest
          - windows-latest
```
 but the `nightly` test failed because of [ApproxFun.jl](https://github.com/JuliaApproximation/ApproxFun.jl). (see the [ci.yml](https://github.com/JuliaApproximation/ApproxFun.jl/blob/master/.github/workflows/ci.yml) file of [ApproxFun.jl](https://github.com/JuliaApproximation/ApproxFun.jl) which led to my new test setting).

Release v0.3.1 was succesfully tested using
```
      matrix:
        version:
          - '1.7' 
          # - '1' 
          # - '^1.8.0-0'
          # - 'nightly' 
        os:  
          - ubuntu-latest
          - windows-latest
```
but failed with 
```
      matrix:
        version:
          - '1.7' 
          # - '1' 
          - '^1.8.0-0'
          # - 'nightly' 
        os:  
          - ubuntu-latest
          - windows-latest
```

So, my understanding is that SLICOT_jll_v5.7 was succesfully running with Julia 1.7, 1.8 and Julia `nightly`.
