### ISSUE TITLE
Forerunner only triggers on `build_tarballs.jl`

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/Yggdrasil#6141]
https://github.com/JuliaPackaging/Yggdrasil/blob/b5e9fb6159056fdb775745b1c4d775a04368e031/.buildkite/pipeline.yml#L11

https://github.com/JuliaPackaging/Yggdrasil/pull/6140#issuecomment-1402483971

@staticfloat what I wanted to express is watch every folder containing a build_tarballs.jl

**Comment by staticfloat** [comment]
Let's instead trigger on any change in one of those top-level directories, then use a `path_processor` to coalesce changes down to folders that contain `build_tarballs.jl` files:

```
      - staticfloat/forerunner#v1:
          watch:
            # Watch only changes within our top-level alphabetical directories
            - "[A-Z]/**"
          path_processor: .buildkite/path_processors/per-project
          target: .buildkite/launch_project.yml
          target_type: template
```

The `per-project` file looks something like this:
```
#!/bin/bash

# Initialize the features we need
set -eou pipefail
shopt -s extglob
shopt -s globstar


declare -A PROJECTS
# Helper function to find the directory that contains the `build_tarballs.jl` for the given modified file
function find_project() {
    d="${1}"
    while [[ "${d}" != "$(dirname "${d}")" ]]; do
        if [[ -f "${d}/build_tarballs.jl" ]]; then
            echo "${d}"
            return
        fi
        d="$(dirname "${d}")"
    done
}

# For each changed file, find its "project" (e.g. the directory containing `build_tarballs.jl`)
for f in "$@"; do
    proj="$(find_project "${f}")"
    if [[ -z "${proj}" ]]; then
        buildkite-agent annotate "Unable to find project for ${f}" --style "error"
        continue
    fi
    PROJECTS["${proj}"]=1
done

# Output the build targets
echo "${!PROJECTS[@]}"
```
